# Generated by Django 5.2.15 on 2026-08-04 10:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
        ('workspace', '0002_workspace_unique_workspace_title_per_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preparedness_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('generated_plan', models.JSONField()),
                ('hours_per_day', models.DecimalField(decimal_places=2, max_digits=4)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('quiz_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_schedules', to='quiz.quizattempt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_schedules', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_schedules', to='workspace.workspace')),
            ],
            options={
                'db_table': 'study_schedules',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='study_sched_user_id_1ef6a2_idx'), models.Index(fields=['workspace'], name='study_sched_workspa_95233c_idx'), models.Index(fields=['quiz_attempt'], name='study_sched_quiz_at_9fdec5_idx'), models.Index(fields=['is_active'], name='study_sched_is_acti_1423e8_idx')],
            },
        ),
    ]
