# Generated by Django 5.2.15 on 2026-08-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyschedule',
            name='model_version',
            field=models.CharField(default='v1', max_length=20),
        ),
    ]
