# Generated by Django 5.2.15 on 2026-07-25 13:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0005_alter_file_file_hash_alter_uploadsessionfile_status'),
        ('workspace', '0002_workspace_unique_workspace_title_per_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('stage', models.CharField(choices=[('INITIALIZED', 'Initialized'), ('DOWNLOADING', 'Downloading Files'), ('EXTRACTING', 'Extracting Content'), ('VALIDATING', 'Validating Data'), ('PERSISTING', 'Persisting Data'), ('CLEANING_UP', 'Cleaning Up'), ('FINISHED', 'Finished')], default='INITIALIZED', max_length=30)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='workspace.workspace')),
            ],
            options={
                'db_table': 'processing_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_number', models.PositiveIntegerField()),
                ('question_text', models.TextField()),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='files.file')),
            ],
            options={
                'ordering': ('question_number',),
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='processing.question')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='workspace.workspace')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='QuestionTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_topics', to='processing.question')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_topics', to='processing.topic')),
            ],
        ),
        migrations.CreateModel(
            name='TopicFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='files.file')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='processing.topic')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('source_file', 'question_number'), name='unique_question_per_file'),
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.UniqueConstraint(fields=('question', 'text'), name='unique_option_per_question'),
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.UniqueConstraint(condition=models.Q(('is_correct', True)), fields=('question',), name='single_correct_option_per_question'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='unique_topic_per_workspace'),
        ),
        migrations.AddConstraint(
            model_name='questiontopic',
            constraint=models.UniqueConstraint(fields=('question', 'topic'), name='unique_question_topic'),
        ),
        migrations.AddConstraint(
            model_name='topicfile',
            constraint=models.UniqueConstraint(fields=('topic', 'file'), name='unique_topic_file_link'),
        ),
    ]
