# Generated by Django 5.2.15 on 2026-08-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='time_spent_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizattemptanswer',
            name='time_spent_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
